[package]
name = "mrld"
version = "0.1.11"
edition = "2021"
repository = "https://github.com/phoggy/mrld"

[dependencies]
argh = "0.1.12"
ansi_term = "0.12.1"
zxcvbn = { version = "3.1.0", features = ["ser"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.114", features = ["preserve_order"] }
time = "0.3" # Ensure newer time version (fix for CVE)

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.11.1"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = ["shell", "homebrew"]
# A GitHub repo to push Homebrew formulas to
tap = "phoggy/homebrew-mrld"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Override deprecated default runners
github-custom-runners = { aarch64-apple-darwin = "macos-latest", x86_64-apple-darwin = "macos-latest", x86_64-unknown-linux-gnu = "ubuntu-latest", x86_64-pc-windows-msvc = "windows-latest" }
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
# Publish jobs to run in CI
pr-run-mode = "plan"
# Allow manually-patched workflow (runners updated from deprecated to current)
allow-dirty = ["ci"]

# cargo-dist
